### ISSUE TITLE
Winmerge stuck when comparing folders in Windows 10

### ISSUE THREAD

**Issue by davik3000** [sdottaka/winmerge-v2#18]
In Windows 10, there's an issue when I try to compare two folder on my desktop.

This problem happens inside the application and outside, in Explorer (by selecting the two folders and right click on it).
It open the two-view tab, and the comparison (and the progress bar) stucks at 0%. After that, WinMerge will be completely unstable. I cannot stop the comparison, neither I can close the window. I need to kill the process from the Task Manager.

Windows 10 Enterprise, user without administrative privilegies.
Winmerge v. 2.14.0.118+-jp-118

Please, let me know if and how I can give you more debugging details.

**Comment by sdottaka** [comment]
Thank you for reporting.

It might be the same as the recently reported problem that occurs when comparing folders on machines with more than 16 CPU cores.

The problem has been fixed in latest experimental release.

If so, could you try the latest experimental release from: 
https://github.com/sdottaka/winmerge-v2/releases/tag/2.14.0%2B-jp-126
?

**Comment by sdottaka** [comment]
Closed. If you still have this problem, please reopen this issue.

**Comment by davik3000** [comment]
Many thanks

**Comment by snowjim** [comment]
This problem still exists, have tried several big folders with subfolders and after a while it gets stuck, no error and no more progress. I have to micromanage the compare and choose just a couple of folders at a time. Its a big risk that I might miss some compares.

I have a failing harddrive so I have copied all content to another disk. To get a list of files that did not make it I need to make a compare. The last time it stoped on item 42497 that is a regular jpg file.
